#ifndef EVENTTYPE_H
#define EVENTTYPE_H

// Event Types
enum EventType
{
    EVENT_PIECE_MOVED,
    EVENT_PIECE_MOVED_HIT_PIECE,
    EVENT_PIECE_MOVED_TO_HOME_ROW,
    EVENT_PIECE_MOVED_TO_HOME_SQUARE,
    EVENT_PIECE_MOVED_TO_HOME_SQUARE_HIT_PIECE,
    EVENT_PIECE_MOVED_TO_HOME_SQUARE_FROM_HOME,
    EVENT_PIECE_MOVED_TO_HOME_SQUARE_FROM_HOME_HIT_PIECE,
    EVENT_NO_MOVE
};

#endif
